### ISSUE TITLE
이미지 업로드 에러

### ISSUE THREAD

**Issue by timan1802** [CatsMiaow/KI-Board#1]
1. adm/board.php 파일에서 mkdir 로 디렉토리 생성시 하위생성이 안됨.
   mkdir($board_path, 0707, true) 이런식으로 변경해야 thumb 하위 디렉토리가 생성됨.
2. 업로드시 ' 업로드 경로가 잘못 되었습니다. <-- /index.php/_board/swfupload' 이런 에러 발생하면서 이미지 업로드 안됨.
   _board/swfupload.php 파일에서 $config['upload_path']   = DATA_PATH.'/temp'; 부분을 체크하고 있음.
   해당 디렉토리를 수동으로 생성하고 하니 업로드 잘됨.
3. 업로드가 실패해도 swfupload는 Complete 이 떨어짐. 
   echo $this->upload->display_errors('', ''); <<< 이거랑 return FALSE 부분을 
   header("HTTP/1.0 404 Not Found"); 로 변경 하면 정상적으로 처리.
   swfupload 에서 어떻게 하는 방식 있을 텐데, 잘 몰라서...

**Comment by CatsMiaow** [comment]
오 이곳에 문의를 다 주시다니 :open_mouth:
1,2번 문제는 제 실수네요. Github에 올릴 때 빈 폴더가 안 올라갔네요.
/data
/data/file
/data/member
/data/temp
의 폴더 구조가 생성되어 있으면 문제가 발생하지 않습니다.
3번 제보 감사합니다.

Swfupload는 낡은 라이브러리라 Codeigniter 3.0이 정식 릴리즈될 때 Plupload( http://plupload.com )로 갈아치울 예정입니다. :smiley:

**Comment by CatsMiaow** [comment]
- /data
- /data/file
- /data/member
- /data/temp
